# Generated by Django 2.1.7 on 2019-04-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0017_firewallstate_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallstate',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device'),
        ),
        migrations.AlterField(
            model_name='portscan',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device'),
        ),
    ]
