# Generated by Django 2.1.10 on 2019-07-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0050_deviceinfo_device_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_external_ip_address',
            field=models.GenericIPAddressField(null=True)
        ),
    ]
