# Generated by Django 2.1.10 on 2019-07-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0051_device_last_external_ip_address'),
        ('device_registry', '0051_pairingkey'),
    ]

    operations = [
    ]
