# Generated by Django 2.1.10 on 2019-09-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0055_remove_deviceinfo_trust_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='device',
        ),
        migrations.RemoveField(
            model_name='firewallstate',
            name='device',
        ),
        migrations.RemoveField(
            model_name='portscan',
            name='device',
        ),
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
        migrations.DeleteModel(
            name='FirewallState',
        ),
        migrations.DeleteModel(
            name='PortScan',
        ),
    ]
