# Generated by Django 2.2.6 on 2019-10-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0067_device_mysql_root_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vulnerable_cpu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
