version: '3'
services:
  dash-dev:
    hostname: dash-dev0
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8000:8000'
  api-dev:
    hostname: api-dev0
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8001:8000'
  mtls-api-dev:
    hostname: mtls-api-dev0
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8002:8000'
  nginx-static:
    hostname: wott-static
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '8003:80'
