version: '3'
services:
  migrate:
    command: python manage.py migrate --noinput
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - psql
      - wott-static

  dash-dev:
    hostname: dash-dev0
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
      - DATASTORE_KEY_JSON
    build:
      context: .
    image: wott-api:latest
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - psql
      - migrate
      - wott-static

  api-dev:
    hostname: api-dev0
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
      - DATASTORE_KEY_JSON
    image: api:latest
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8001:8000'
    depends_on:
      - psql
      - migrate

  mtls-api-dev:
    hostname: mtls-api-dev0
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
      - DATASTORE_KEY_JSON
    build:
      context: .
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '8002:8000'
    depends_on:
      - psql
      - migrate

  wott-static:
    hostname: wott-static
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        DJANGO_SETTINGS_MODULE: backend.settings.dev
    image: wott-static:latest
    ports:
      - '8003:80'

  psql:
    environment:
      - POSTGRES_DB=wott-backend
      - POSTGRES_PASSWORD=SuperSecurePassword
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=SuperSecurePassword
      - RABBITMQ_DEFAULT_VHOST=wott-dash
    ports:
      - '5672:5672'

  celery:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
      - RABBIT_HOST=rabbit
      - RABBIT_USER=user
      - RABBIT_PASSWORD=SuperSecurePassword
      - RABBIT_VHOST=wott-dash
    build:
      context: .
    command: celery worker -A backend -l error --time-limit=90 --soft-time-limit=60 --pidfile="/tmp/celery.pid"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - psql
      - migrate
      - rabbit

  celery-beat:
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - DB_PASSWORD=SuperSecurePassword
      - DB_USER=postgres
      - RABBIT_HOST=rabbit
      - RABBIT_USER=user
      - RABBIT_PASSWORD=SuperSecurePassword
      - RABBIT_VHOST=wott-dash
    build:
      context: .
    command: celery beat -A backend -l error --pidfile="/tmp/celery.pid" -s "/tmp/celerybeat-schedule"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - psql
      - migrate
      - rabbit

volumes:
  db-data:

networks:
  default:
    external:
      name: wott
