version: '3'
services:
  api-dev:
    command: python manage.py test
    hostname: api-test
    environment:
    - DJANGO_SETTINGS_MODULE=backend.settings.tests
    build:
      context: .
    depends_on:
      - psql
  psql:
    environment:
      - POSTGRES_DB=wott-backend
      - POSTGRES_PASSWORD=SuperSecurePassword
    image: postgres:alpine
