version: 2
jobs:
  build:
    docker:
      - image: gcr.io/wott-prod/wott-api
        auth:
          username: _json_key
          password: $GCR_CREDS
        environment:
          DJANGO_SETTINGS_MODULE: backend.settings.dev
    working_directory: /tmp
    steps:
      - run:
          name: Run tests
          command: |
            cd /usr/src/app
            python manage.py test
