apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: le-secret-install-redirect
  namespace: api
spec:
  secretName: le-secret-install-redirect
  issuerRef:
    name: letsencrypt-prod
  commonName: install.wott.io
