# Generated by Django 2.2.7 on 2019-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_profile_first_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_name',
            field=models.CharField(blank=True, max_length=39),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_repo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
