# Generated by Django 2.2.8 on 2019-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0013_profile_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free (1 node limit)'), (2, 'Standard (paid per-node)'), (3, 'Enterprise')], default=1),
        ),
    ]
