# Generated by Django 2.2.8 on 2019-12-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0014_auto_20191212_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paid_nodes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free (1 node limit)'), (2, 'Standard (paid per-node) with 1 month free trial'), (3, 'Enterprise')], default=1),
        ),
    ]
