# Generated by Django 2.2.8 on 2019-12-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0015_auto_20191213_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid_nodes',
        ),
    ]
