# Generated by Django 2.2.9 on 2020-01-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0016_remove_profile_paid_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unlimited_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free (1 node limit)'), (2, 'Standard (paid per node) with 1 month free trial'), (3, 'Enterprise')], default=1),
        ),
    ]
