apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.service.celery.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.celery.name }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.service.celery.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.celery.name }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - name: {{ .Values.service.celery.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - "worker"
            - "--app=backend"
            - "--loglevel=info"
            - "--time-limit=90"
            - "--soft-time-limit=60"
            - "--pidfile=/tmp/celery.pid"
          env:
            - name: RELEASE_TRIGGER
              value: "{{ .Values.releaseTimeStamp }}"
            - name: DEBUG
              value: "{{ .Values.service.api.debug }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: djangoSecretKey
            - name: DB_HOST
              value: "{{ .Values.databaseHost }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: databasePassword
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: sentryDsn
            - name: REDIS_HOST
              value: {{ .Values.redisHost }}
            - name: GITHUB_APP_PEM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: githubAppPem
            - name: GITHUB_APP_ID
              value: "{{ .Values.integrations.github.appId }}"
            - name: GITHUB_APP_NAME
              value: "{{ .Values.integrations.github.appName }}"
            - name: GITHUB_APP_CLIENT_ID
              value: "{{ .Values.integrations.github.appClientId }}"
            - name: GITHUB_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: githubAppClientSecret
            - name: GITHUB_APP_REDIRECT_URL
              value: "{{ .Values.integrations.github.appRedirectUrl }}"
          resources:
{{ toYaml .Values.resources.celery | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
