apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.service.dash.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.dash.name }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.dash.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.dash.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.service.dash.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.dash.name }}
              containerPort: {{ .Values.service.dash.internalPort }}
              protocol: TCP
          env:
            - name: RELEASE_TRIGGER
              value: "{{ .Values.releaseTimeStamp }}"
            - name: DEBUG
              value: "{{ .Values.service.dash.debug }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: djangoSecretKey
            - name: DB_HOST
              value: "{{ .Values.databaseHost }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: databasePassword
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiSecrets }}
                  key: sentryDsn
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.dash.internalPort }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.dash.internalPort }}
            initialDelaySeconds: 20
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
