{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "api.name" . }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: le-secret
  {{- end }}
{{- end }}
  rules:
    - host: "dash.wott.io"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.service.dash.name }}
              servicePort: {{ .Values.service.dash.externalPort }}
{{- end }}
