{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "install-redirect"
  namespace: {{ .Values.namespace }}
  labels:
    app: "install-redirect"
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
        if ($request_uri !~ "^/.well-known/acme-challenge/.*")
        {
        return 301 https://raw.githubusercontent.com/WoTTsecurity/agent/master/bin/install.sh;
        }
spec:
  tls:
    - hosts:
      - "install.wott.io"
      secretName: le-secret-install-redirect
  rules:
    - host: "install.wott.io"
{{- end }}
