apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "api.name" . }}
    chart: {{ include "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.externalPort }}
      targetPort: {{ .Values.service.api.internalPort }}
      protocol: TCP
      name: {{ .Values.service.api.name }}
  selector:
    app: {{ .Values.service.api.name }}
    release: {{ .Release.Name }}
